<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Section 1 Geometry in \(R^n\) | 09-geometry.utf8</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Section 1 Geometry in \(R^n\) | 09-geometry.utf8" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Section 1 Geometry in \(R^n\) | 09-geometry.utf8" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */
</style>

<link rel="stylesheet" href="m236.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href = "./">MATH 236: Linear Algebra</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path=""><a href="#geometry-in-rn"><i class="fa fa-check"></i><b>1</b> Geometry in <span class="math inline">\(R^n\)</span></a><ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#rotation-dilation"><i class="fa fa-check"></i><b>1.1</b> Rotation-Dilation</a><ul>
<li class="chapter" data-level="1.1.1" data-path=""><a href="#example-1"><i class="fa fa-check"></i><b>1.1.1</b> Example 1</a></li>
<li class="chapter" data-level="1.1.2" data-path=""><a href="#example-2"><i class="fa fa-check"></i><b>1.1.2</b> Example 2</a></li>
<li class="chapter" data-level="1.1.3" data-path=""><a href="#example-3"><i class="fa fa-check"></i><b>1.1.3</b> Example 3</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#general-2x2-matrices-with-complex-eigenvalues"><i class="fa fa-check"></i><b>1.2</b> General 2x2 Matrices with Complex Eigenvalues</a></li>
<li class="chapter" data-level="1.3" data-path=""><a href="#a-3d-example"><i class="fa fa-check"></i><b>1.3</b> A 3D example</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<!--bookdown:title:end-->
<!--bookdown:title:start-->
<div id="geometry-in-rn" class="section level1">
<h1><span class="header-section-number">Section 1</span> Geometry in <span class="math inline">\(R^n\)</span></h1>
<p><a href="https://github.com/Tom-Halverson/math236_s21/blob/main/08-complex-eigenvalues.Rmd">Download this Rmd file</a></p>
<p>Now we will explore what happens if the matrix has complex eigenvalues.</p>
<div id="rotation-dilation" class="section level2">
<h2><span class="header-section-number">1.1</span> Rotation-Dilation</h2>
<p>First we explore a special case of 2x2 matrices with complex eigenvalues of the following form:
<span class="math display">\[
R=\begin{bmatrix}
a &amp; -b \\
b &amp; a \\
\end{bmatrix}
\]</span>
As we see in the image below, this matrix rotates by angle of <span class="math inline">\(\theta\)</span> and expands (dilates) or contracts by a factor of <span class="math inline">\(r\)</span> where
<span class="math display">\[
\begin{align}
\theta &amp;= \arctan(b/a) \\
r &amp;= \sqrt{a^2 + b^2}
\end{align}
\]</span>
<img src="images/rotation-dilation.png" style="width:75.0%" /></p>
<p>Furthermore the eigenvalues of this matrix are the complex values
<span class="math display">\[
\lambda_1 = a + b i \qquad \lambda_2 = a - b i
\]</span>
where <span class="math inline">\(i = \sqrt{-1}\)</span>. These eigenvalues are conjugate pairs and are often written as
<span class="math inline">\(\lambda = a \pm b i\)</span>. They come from applying the quadratic formula to the characteristic polynomial and getting a negative discriminant under the square root. It is important to note that both <strong>the angle of rotation <span class="math inline">\(\theta\)</span> and the dilation factor <span class="math inline">\(r\)</span> are contained in the eigenvalues.</strong> The fact that these are the eigenvalues is derived in the video. We will illustrate it here in three examples.</p>
<div id="example-1" class="section level3">
<h3><span class="header-section-number">1.1.1</span> Example 1</h3>
<p>Our first example has <span class="math inline">\(a = .9\)</span> and <span class="math inline">\(b = .2\)</span>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>(<span class="dt">A =</span> <span class="kw">cbind</span>(<span class="kw">c</span>(.<span class="dv">9</span>,.<span class="dv">2</span>),<span class="kw">c</span>(<span class="op">-</span>.<span class="dv">2</span>,.<span class="dv">9</span>)))</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]  0.9 -0.2
## [2,]  0.2  0.9</code></pre>
<p>We look at its eigenvectors and eigenvalues and see that <span class="math inline">\(\lambda = .9 \pm .2 i\)</span>:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="kw">eigen</span>(A)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 0.9+0.2i 0.9-0.2i
## 
## $vectors
##                      [,1]                 [,2]
## [1,] 0.7071068+0.0000000i 0.7071068+0.0000000i
## [2,] 0.0000000-0.7071068i 0.0000000+0.7071068i</code></pre>
<p>Notics that the eigenvectors also come in conjugate pairs, with a real and a complex part. This always happens.
<span class="math display">\[
\vec{\mathsf{v}} = 
\begin{bmatrix}0.707 \\ 0.000 \end{bmatrix} \pm 
\begin{bmatrix} 0.000 \\ .707 \end{bmatrix}  i
\]</span>
Now, let’s find the <strong>angle of rotation</strong>. We will use the <code>Arg</code> command which finds the angle (in radians) of a complex number. We also convert it to degrees here.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>vals =<span class="st"> </span><span class="kw">eigen</span>(A)<span class="op">$</span>values</span>
<span id="cb5-2"><a href="#cb5-2"></a>v1 =<span class="st"> </span>vals[<span class="dv">1</span>]</span>
<span id="cb5-3"><a href="#cb5-3"></a><span class="kw">Arg</span>(v1)  <span class="co"># gives the argument, or angle, of a complex number (in radians)</span></span></code></pre></div>
<pre><code>## [1] 0.2186689</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="kw">Arg</span>(v1) <span class="op">/</span><span class="st"> </span>(<span class="dv">2</span><span class="op">*</span>pi) <span class="op">*</span><span class="st"> </span><span class="dv">360</span> <span class="co"># convert to degrees</span></span></code></pre></div>
<pre><code>## [1] 12.52881</code></pre>
<p>For good measure, we can compare with using the <code>arctan</code> function.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="kw">atan</span>(.<span class="dv">2</span><span class="op">/</span>.<span class="dv">9</span>)  </span></code></pre></div>
<pre><code>## [1] 0.2186689</code></pre>
<p>Next we find the <strong>dilation/contraction factor</strong>. We can do so using the <code>Mod</code> command, which finds the “modulus” or absolute value or length of a complex number.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="kw">Mod</span>(v1) <span class="co"># gives the length of a complex number</span></span></code></pre></div>
<pre><code>## [1] 0.9219544</code></pre>
<p>And, again for good measure, we compare with using the Pythagorean theorem:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="kw">sqrt</span>(.<span class="dv">9</span><span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="fl">.2</span><span class="op">^</span><span class="dv">2</span>)  </span></code></pre></div>
<pre><code>## [1] 0.9219544</code></pre>
<p>Now, we observe the trajectory of a single point <span class="math inline">\((0,1)^T\)</span> under this matrix. In this picture you can see that it is contracting and rotating by 12.5 degrees. Note that 360/12.5 is about 29, and it takes 29 applications to go once around the circle. You can count them in the plot below. Furthermore, <span class="math inline">\((0.9219544)^29 =0.095\)</span> and after 29 applications the vector is about 1/10 of its original length.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a>N =<span class="st"> </span><span class="dv">50</span></span>
<span id="cb15-2"><a href="#cb15-2"></a>start =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb15-3"><a href="#cb15-3"></a>X =<span class="st"> </span><span class="kw">matrix</span>(<span class="dv">0</span>,<span class="dt">nrow=</span><span class="dv">2</span>,<span class="dt">ncol=</span>N)</span>
<span id="cb15-4"><a href="#cb15-4"></a>X[,<span class="dv">1</span>] =<span class="st"> </span>start</span>
<span id="cb15-5"><a href="#cb15-5"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span>N) {X[,i] =<span class="st"> </span>A <span class="op">%*%</span><span class="st"> </span>X[,i<span class="dv">-1</span>]}</span>
<span id="cb15-6"><a href="#cb15-6"></a></span>
<span id="cb15-7"><a href="#cb15-7"></a><span class="kw">plot</span>(X[<span class="dv">1</span>,],X[<span class="dv">2</span>,],<span class="dt">col=</span><span class="st">&#39;blue&#39;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>),<span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>),<span class="dt">xlab=</span><span class="st">&#39;x&#39;</span>,<span class="dt">ylab=</span><span class="st">&#39;y&#39;</span>,<span class="dt">pch=</span><span class="dv">20</span>,<span class="dt">cex=</span><span class="dv">1</span>)</span>
<span id="cb15-8"><a href="#cb15-8"></a><span class="kw">points</span>(start[<span class="dv">1</span>],start[<span class="dv">2</span>],<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb15-9"><a href="#cb15-9"></a><span class="kw">grid</span>(<span class="dt">nx=</span><span class="dv">10</span>,<span class="dt">ny=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="09-geometry_files/figure-html/unnamed-chunk-7-1.png" width="576" />
We can also view this by looking at a plot of the x and y coordinates over time as the point (x,y) circles around in the xy-plane. Key point: complex eigenvalues lead to oscillating values of the individual coordinates</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>t =<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span>,N)</span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="kw">plot</span>(t,X[<span class="dv">1</span>,],<span class="dt">type=</span><span class="st">&#39;l&#39;</span>,<span class="dt">col=</span><span class="st">&#39;blue&#39;</span>,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>),<span class="dt">ylab=</span><span class="st">&quot;x and y coordinates&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;t (time) &quot;</span>)</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="kw">lines</span>(t,X[<span class="dv">2</span>,],<span class="dt">col=</span><span class="st">&#39;darkorange&#39;</span>)</span>
<span id="cb16-4"><a href="#cb16-4"></a><span class="kw">legend</span>(<span class="dv">15</span>, <span class="fl">0.8</span>, <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;x&quot;</span>, <span class="st">&quot;y&quot;</span>), <span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;darkorange&quot;</span>), <span class="dt">lty=</span><span class="dv">1</span>)</span></code></pre></div>
<p><img src="09-geometry_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>We can also use <code>trajectory_plot</code> from [Dynamical Systems in 2D] to watch what happens to a whole grid of points under this transformation. It is beautiful!</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="kw">trajectory_plot</span>(A, <span class="dt">t=</span><span class="dv">30</span>, <span class="dt">datamax=</span><span class="dv">5</span>, <span class="dt">plotmax=</span><span class="dv">5</span>, <span class="dt">numpoints=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="09-geometry_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="example-2" class="section level3">
<h3><span class="header-section-number">1.1.2</span> Example 2</h3>
<p>Here is a second example of a rotation-dilation matrix, this time with <span class="math inline">\(a = .96\)</span> and <span class="math inline">\(b = .28\)</span>.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>(<span class="dt">A =</span> <span class="kw">cbind</span>(<span class="kw">c</span>(.<span class="dv">96</span>,.<span class="dv">28</span>),<span class="kw">c</span>(<span class="op">-</span>.<span class="dv">28</span>,.<span class="dv">96</span>)))</span></code></pre></div>
<pre><code>##      [,1]  [,2]
## [1,] 0.96 -0.28
## [2,] 0.28  0.96</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="kw">eigen</span>(A)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 0.96+0.28i 0.96-0.28i
## 
## $vectors
##                      [,1]                 [,2]
## [1,] 0.7071068+0.0000000i 0.7071068+0.0000000i
## [2,] 0.0000000-0.7071068i 0.0000000+0.7071068i</code></pre>
<p>We check the angle of rotation and the dilation factor</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>vals =<span class="st"> </span><span class="kw">eigen</span>(A)<span class="op">$</span>values</span>
<span id="cb22-2"><a href="#cb22-2"></a>v1 =<span class="st"> </span>vals[<span class="dv">1</span>]</span>
<span id="cb22-3"><a href="#cb22-3"></a><span class="kw">Arg</span>(v1)  <span class="co"># gives the argument, or angle, of a complex number (in radians)</span></span></code></pre></div>
<pre><code>## [1] 0.2837941</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="kw">Arg</span>(v1) <span class="op">/</span><span class="st"> </span>(<span class="dv">2</span><span class="op">*</span>pi) <span class="op">*</span><span class="st"> </span><span class="dv">360</span> <span class="co"># convert to degrees</span></span></code></pre></div>
<pre><code>## [1] 16.2602</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="kw">Mod</span>(v1)  <span class="co"># gives the length of a complex number</span></span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>Notice that the dilation factor is 1, which is seen in the following plots. Here are 21 iterations:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="co"># plot</span></span>
<span id="cb28-2"><a href="#cb28-2"></a>N =<span class="st"> </span><span class="dv">21</span></span>
<span id="cb28-3"><a href="#cb28-3"></a>start =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb28-4"><a href="#cb28-4"></a>X =<span class="st"> </span><span class="kw">matrix</span>(<span class="dv">0</span>,<span class="dt">nrow=</span><span class="dv">2</span>,<span class="dt">ncol=</span>N)</span>
<span id="cb28-5"><a href="#cb28-5"></a>X[,<span class="dv">1</span>] =<span class="st"> </span>start</span>
<span id="cb28-6"><a href="#cb28-6"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span>N) {X[,i] =<span class="st"> </span>A <span class="op">%*%</span><span class="st"> </span>X[,i<span class="dv">-1</span>]}</span>
<span id="cb28-7"><a href="#cb28-7"></a></span>
<span id="cb28-8"><a href="#cb28-8"></a><span class="kw">plot</span>(X[<span class="dv">1</span>,],X[<span class="dv">2</span>,],<span class="dt">col=</span><span class="st">&#39;blue&#39;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>),<span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>),<span class="dt">xlab=</span><span class="st">&#39;x&#39;</span>,<span class="dt">ylab=</span><span class="st">&#39;y&#39;</span>,<span class="dt">pch=</span><span class="dv">20</span>,<span class="dt">cex=</span><span class="dv">1</span>)</span>
<span id="cb28-9"><a href="#cb28-9"></a><span class="kw">points</span>(start[<span class="dv">1</span>],start[<span class="dv">2</span>],<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb28-10"><a href="#cb28-10"></a><span class="kw">grid</span>(<span class="dt">nx=</span><span class="dv">10</span>,<span class="dt">ny=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="09-geometry_files/figure-html/unnamed-chunk-13-1.png" width="576" /></p>
<p>And here are 200 iterations</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="co"># plot</span></span>
<span id="cb29-2"><a href="#cb29-2"></a>N =<span class="st"> </span><span class="dv">200</span></span>
<span id="cb29-3"><a href="#cb29-3"></a>start =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb29-4"><a href="#cb29-4"></a>X =<span class="st"> </span><span class="kw">matrix</span>(<span class="dv">0</span>,<span class="dt">nrow=</span><span class="dv">2</span>,<span class="dt">ncol=</span>N)</span>
<span id="cb29-5"><a href="#cb29-5"></a>X[,<span class="dv">1</span>] =<span class="st"> </span>start</span>
<span id="cb29-6"><a href="#cb29-6"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span>N) {X[,i] =<span class="st"> </span>A <span class="op">%*%</span><span class="st"> </span>X[,i<span class="dv">-1</span>]}</span>
<span id="cb29-7"><a href="#cb29-7"></a></span>
<span id="cb29-8"><a href="#cb29-8"></a><span class="kw">plot</span>(X[<span class="dv">1</span>,],X[<span class="dv">2</span>,],<span class="dt">col=</span><span class="st">&#39;blue&#39;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>),<span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>),<span class="dt">xlab=</span><span class="st">&#39;x&#39;</span>,<span class="dt">ylab=</span><span class="st">&#39;y&#39;</span>,<span class="dt">pch=</span><span class="dv">20</span>,<span class="dt">cex=</span><span class="dv">1</span>)</span>
<span id="cb29-9"><a href="#cb29-9"></a><span class="kw">points</span>(start[<span class="dv">1</span>],start[<span class="dv">2</span>],<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb29-10"><a href="#cb29-10"></a><span class="kw">grid</span>(<span class="dt">nx=</span><span class="dv">10</span>,<span class="dt">ny=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="09-geometry_files/figure-html/unnamed-chunk-14-1.png" width="576" /></p>
<p>And a trajectory plot:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="kw">trajectory_plot</span>(A, <span class="dt">t=</span><span class="dv">30</span>, <span class="dt">datamax=</span><span class="dv">5</span>, <span class="dt">plotmax=</span><span class="dv">5</span>, <span class="dt">numpoints=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="09-geometry_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="example-3" class="section level3">
<h3><span class="header-section-number">1.1.3</span> Example 3</h3>
<p>A third and final example.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a>(<span class="dt">A =</span> <span class="kw">cbind</span>(<span class="kw">c</span>(.<span class="dv">99</span>,.<span class="dv">16</span>),<span class="kw">c</span>(<span class="op">-</span>.<span class="dv">16</span>,.<span class="dv">99</span>)))</span></code></pre></div>
<pre><code>##      [,1]  [,2]
## [1,] 0.99 -0.16
## [2,] 0.16  0.99</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a><span class="kw">eigen</span>(A)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 0.99+0.16i 0.99-0.16i
## 
## $vectors
##                       [,1]                  [,2]
## [1,]  0.0000000-0.7071068i  0.0000000+0.7071068i
## [2,] -0.7071068+0.0000000i -0.7071068+0.0000000i</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a>vals =<span class="st"> </span><span class="kw">eigen</span>(A)<span class="op">$</span>values</span>
<span id="cb35-2"><a href="#cb35-2"></a>v1 =<span class="st"> </span>vals[<span class="dv">1</span>]</span>
<span id="cb35-3"><a href="#cb35-3"></a><span class="kw">Arg</span>(v1) <span class="op">/</span><span class="st"> </span>(<span class="dv">2</span><span class="op">*</span>pi) <span class="op">*</span><span class="st"> </span><span class="dv">360</span> <span class="co"># convert to degrees</span></span></code></pre></div>
<pre><code>## [1] 9.180542</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="kw">Mod</span>(v1)  <span class="co"># gives the length of a complex number</span></span></code></pre></div>
<pre><code>## [1] 1.002846</code></pre>
<p>We see that the dilation factor is <span class="math inline">\(r = 1.0028\)</span> and the angle of rotation is <span class="math inline">\(9.18\)</span> degrees. Here are 100 iterations.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="co"># plot</span></span>
<span id="cb39-2"><a href="#cb39-2"></a>N =<span class="st"> </span><span class="dv">100</span></span>
<span id="cb39-3"><a href="#cb39-3"></a>start =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb39-4"><a href="#cb39-4"></a>X =<span class="st"> </span><span class="kw">matrix</span>(<span class="dv">0</span>,<span class="dt">nrow=</span><span class="dv">2</span>,<span class="dt">ncol=</span>N)</span>
<span id="cb39-5"><a href="#cb39-5"></a>X[,<span class="dv">1</span>] =<span class="st"> </span>start</span>
<span id="cb39-6"><a href="#cb39-6"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span>N) {X[,i] =<span class="st"> </span>A <span class="op">%*%</span><span class="st"> </span>X[,i<span class="dv">-1</span>]}</span>
<span id="cb39-7"><a href="#cb39-7"></a></span>
<span id="cb39-8"><a href="#cb39-8"></a><span class="kw">plot</span>(X[<span class="dv">1</span>,],X[<span class="dv">2</span>,],<span class="dt">col=</span><span class="st">&#39;blue&#39;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>,<span class="dv">2</span>),<span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>,<span class="dv">2</span>),<span class="dt">xlab=</span><span class="st">&#39;x&#39;</span>,<span class="dt">ylab=</span><span class="st">&#39;y&#39;</span>,<span class="dt">pch=</span><span class="dv">20</span>,<span class="dt">cex=</span><span class="dv">1</span>)</span>
<span id="cb39-9"><a href="#cb39-9"></a><span class="kw">points</span>(start[<span class="dv">1</span>],start[<span class="dv">2</span>],<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb39-10"><a href="#cb39-10"></a><span class="kw">grid</span>(<span class="dt">nx=</span><span class="dv">10</span>,<span class="dt">ny=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="09-geometry_files/figure-html/unnamed-chunk-17-1.png" width="576" /></p>
<p>And a trajectory plot:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="kw">trajectory_plot</span>(A, <span class="dt">t=</span><span class="dv">100</span>, <span class="dt">datamax=</span><span class="dv">5</span>, <span class="dt">plotmax=</span><span class="dv">5</span>, <span class="dt">numpoints=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="09-geometry_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
</div>
</div>
<div id="general-2x2-matrices-with-complex-eigenvalues" class="section level2">
<h2><span class="header-section-number">1.2</span> General 2x2 Matrices with Complex Eigenvalues</h2>
<p>Now suppose we have a 2x2 matrix with complex eigenvalues <span class="math inline">\(\lambda = a \pm b i\)</span> and complex eigenvectors <span class="math inline">\(\mathsf{v} = \mathsf{u } \pm \mathsf{w} i\)</span> that is not in rotation-dilation form. Here is an example:
<span class="math display">\[
A = \begin{bmatrix} 1.19 &amp; -0.38 \\ 0.29 &amp; 0.78 \end{bmatrix}
\]</span>
It has eigenvalues and eigenvectors
<span class="math display">\[
\lambda = 0.985 \pm 0.261 i \qquad \mathsf{v} = 
\begin{bmatrix} 0.753 \\ 0.406 \end{bmatrix} \pm 
\begin{bmatrix} 0.000 \\ -0.517 \end{bmatrix} i
\]</span>
as seen here:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>(<span class="dt">A =</span> <span class="kw">cbind</span>(<span class="kw">c</span>(<span class="fl">1.19</span>,<span class="fl">0.29</span>),<span class="kw">c</span>(<span class="op">-</span>.<span class="dv">38</span>,.<span class="dv">78</span>)))</span></code></pre></div>
<pre><code>##      [,1]  [,2]
## [1,] 1.19 -0.38
## [2,] 0.29  0.78</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a><span class="kw">eigen</span>(A)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1] 0.985+0.2611034i 0.985-0.2611034i
## 
## $vectors
##                      [,1]                 [,2]
## [1,] 0.7531030+0.0000000i 0.7531030+0.0000000i
## [2,] 0.4062793-0.5174679i 0.4062793+0.5174679i</code></pre>
<p>The angle of rotation and factor of dilation are <span class="math inline">\(\theta = 14.8\)</span> degrees and <span class="math inline">\(r = 1.019\)</span> as we see from these computations:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a>vals =<span class="st"> </span><span class="kw">eigen</span>(A)<span class="op">$</span>values</span>
<span id="cb45-2"><a href="#cb45-2"></a>v1 =<span class="st"> </span>vals[<span class="dv">1</span>]</span>
<span id="cb45-3"><a href="#cb45-3"></a><span class="kw">Arg</span>(v1) <span class="op">/</span><span class="st"> </span>(<span class="dv">2</span><span class="op">*</span>pi) <span class="op">*</span><span class="st"> </span><span class="dv">360</span> <span class="co"># convert to degrees</span></span></code></pre></div>
<pre><code>## [1] 14.84649</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a><span class="kw">Mod</span>(v1)  <span class="co"># gives the length of a complex number</span></span></code></pre></div>
<pre><code>## [1] 1.019019</code></pre>
<p>A trajectory plot shows us that it is still rotating by 14.8 degrees and dilating by 1.019, but it is taking more of an elliptical pattern.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1"></a>A =<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="fl">1.19</span>,<span class="fl">0.29</span>),<span class="kw">c</span>(<span class="op">-</span>.<span class="dv">38</span>,.<span class="dv">78</span>))</span>
<span id="cb49-2"><a href="#cb49-2"></a>vecs =<span class="st"> </span><span class="kw">eigen</span>(A)<span class="op">$</span>vectors</span>
<span id="cb49-3"><a href="#cb49-3"></a>u =<span class="st"> </span><span class="kw">Re</span>(vecs[,<span class="dv">1</span>])</span>
<span id="cb49-4"><a href="#cb49-4"></a>w =<span class="st"> </span><span class="kw">Im</span>(vecs[,<span class="dv">1</span>])</span>
<span id="cb49-5"><a href="#cb49-5"></a>N =<span class="st"> </span><span class="dv">50</span></span>
<span id="cb49-6"><a href="#cb49-6"></a>start =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb49-7"><a href="#cb49-7"></a>X =<span class="st"> </span><span class="kw">matrix</span>(<span class="dv">0</span>,<span class="dt">nrow=</span><span class="dv">2</span>,<span class="dt">ncol=</span>N)</span>
<span id="cb49-8"><a href="#cb49-8"></a>X[,<span class="dv">1</span>] =<span class="st"> </span>start</span>
<span id="cb49-9"><a href="#cb49-9"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span>N) {X[,i] =<span class="st"> </span>A <span class="op">%*%</span><span class="st"> </span>X[,i<span class="dv">-1</span>]}</span>
<span id="cb49-10"><a href="#cb49-10"></a></span>
<span id="cb49-11"><a href="#cb49-11"></a><span class="kw">plot</span>(X[<span class="dv">1</span>,],X[<span class="dv">2</span>,],<span class="dt">col=</span><span class="st">&#39;blue&#39;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>,<span class="dv">3</span>),<span class="dt">ylim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>,<span class="dv">3</span>),<span class="dt">xlab=</span><span class="st">&#39;x&#39;</span>,<span class="dt">ylab=</span><span class="st">&#39;y&#39;</span>,<span class="dt">pch=</span><span class="dv">20</span>,<span class="dt">cex=</span><span class="dv">1</span>)</span>
<span id="cb49-12"><a href="#cb49-12"></a><span class="kw">points</span>(start[<span class="dv">1</span>],start[<span class="dv">2</span>],<span class="dt">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb49-13"><a href="#cb49-13"></a><span class="kw">lines</span>(<span class="kw">c</span>(<span class="dv">10</span><span class="op">*</span>u[<span class="dv">1</span>],<span class="op">-</span><span class="dv">10</span><span class="op">*</span>u[<span class="dv">1</span>]),<span class="kw">c</span>(<span class="dv">10</span><span class="op">*</span>u[<span class="dv">2</span>],<span class="op">-</span><span class="dv">10</span><span class="op">*</span>u[<span class="dv">2</span>]),<span class="dt">col=</span><span class="st">&quot;purple&quot;</span>)</span>
<span id="cb49-14"><a href="#cb49-14"></a><span class="kw">lines</span>(<span class="kw">c</span>(<span class="dv">10</span><span class="op">*</span>w[<span class="dv">1</span>],<span class="op">-</span><span class="dv">10</span><span class="op">*</span>w[<span class="dv">1</span>]),<span class="kw">c</span>(<span class="dv">10</span><span class="op">*</span>w[<span class="dv">2</span>],<span class="op">-</span><span class="dv">10</span><span class="op">*</span>w[<span class="dv">2</span>]),<span class="dt">col=</span><span class="st">&quot;purple&quot;</span>)</span>
<span id="cb49-15"><a href="#cb49-15"></a><span class="kw">grid</span>(<span class="dt">nx=</span><span class="dv">10</span>,<span class="dt">ny=</span><span class="dv">10</span>)</span></code></pre></div>
<p><img src="09-geometry_files/figure-html/unnamed-chunk-21-1.png" width="576" /></p>
<p>To see precisely what happens, we change to basis <span class="math inline">\(\{\mathsf{w}, \mathsf{u}\}\)</span> where <span class="math inline">\(\mathsf{w}\)</span> and <span class="math inline">\(\mathsf{u}\)</span> are the imaginary and real parts of the eigenvector <span class="math inline">\(\mathsf{v} =\mathsf{u} + \mathsf{w} i\)</span>. In this case the eigenvalues and eigenvectors are
<span class="math display">\[
\lambda = 0.985 \pm 0.261 i \qquad \mathsf{v} = 
\begin{bmatrix} 0.753 \\ 0.406 \end{bmatrix} \pm 
\begin{bmatrix} 0.000 \\ -0.517 \end{bmatrix} i
\]</span>
So if we make the change of basis matrix <span class="math inline">\(P = [\mathsf{u},\mathsf{w}]\)</span>
<span class="math display">\[
P = \begin{bmatrix}
0.000 &amp;  0.753 \\
-0.517 &amp; 0.406 \end{bmatrix}
\]</span>
then we can factor <span class="math inline">\(A\)</span> as
<span class="math display">\[
A = \begin{bmatrix} 1.19 &amp; -0.38 \\ 0.29 &amp; 0.78 \end{bmatrix} = 
\underbrace{\begin{bmatrix}0.000 &amp;  0.753 \\-0.517 &amp; 0.406 \end{bmatrix}}_P
\underbrace{\begin{bmatrix} 0.985 &amp; - 0.261 \\ 0.261 &amp; 0.985 \end{bmatrix}}_R
\underbrace{\begin{bmatrix}0.000 &amp;  0.753 \\-0.517 &amp; 0.406 \end{bmatrix}^{-1}}_{P^{-1}}
\]</span>
We have not diagonalized <span class="math inline">\(A\)</span>. Rather we have <strong>rotation-dilationalized</strong> (made up term) the matrix <span class="math inline">\(A\)</span>. At is <em>core</em> <span class="math inline">\(A\)</span> is a rotation-dilation matrix whose angle and dilation factor come from the eigenvalue. The matrix <span class="math inline">\(P\)</span> is a change of basis matrix. It is rotating and dilating in this new coordinate system, which are the vectors in the plot above.</p>
<p>If we multiply the other way, we get
<span class="math display">\[
P^{-1} A P = \begin{bmatrix} 0.985 &amp; - 0.261 \\ 0.261 &amp; 0.985 \end{bmatrix} = R
\]</span>
Which we can see using R</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a>vecs =<span class="st"> </span><span class="kw">eigen</span>(A)<span class="op">$</span>vectors</span>
<span id="cb50-2"><a href="#cb50-2"></a>P =<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">Im</span>(vecs[,<span class="dv">1</span>]),<span class="kw">Re</span>(vecs[,<span class="dv">2</span>]))</span>
<span id="cb50-3"><a href="#cb50-3"></a>P</span></code></pre></div>
<pre><code>##            [,1]      [,2]
## [1,]  0.0000000 0.7531030
## [2,] -0.5174679 0.4062793</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a><span class="kw">solve</span>(P) <span class="op">%*%</span><span class="st"> </span>A <span class="op">%*%</span><span class="st"> </span>P</span></code></pre></div>
<pre><code>##           [,1]       [,2]
## [1,] 0.9850000 -0.2611034
## [2,] 0.2611034  0.9850000</code></pre>
</div>
<div id="a-3d-example" class="section level2">
<h2><span class="header-section-number">1.3</span> A 3D example</h2>
<p>Here is the Northern Spotted Owl matrices from the [Eigenvalues] examples. We saw that it has one real and two complex eigenvalues:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a>A =<span class="st"> </span><span class="kw">cbind</span>(<span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.18</span>,<span class="dv">0</span>),<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,.<span class="dv">71</span>),<span class="kw">c</span>(<span class="fl">0.33</span>,<span class="dv">0</span>,<span class="fl">0.94</span>))</span>
<span id="cb54-2"><a href="#cb54-2"></a><span class="kw">eigen</span>(A)</span></code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1]  0.9835927+0.0000000i -0.0217964+0.2059185i -0.0217964-0.2059185i
## 
## $vectors
##               [,1]                  [,2]                  [,3]
## [1,] 0.31754239+0i  0.6820937+0.0000000i  0.6820937+0.0000000i
## [2,] 0.05811107+0i -0.0624124-0.5896338i -0.0624124+0.5896338i
## [3,] 0.94646180+0i -0.0450520+0.4256233i -0.0450520-0.4256233i</code></pre>
<p>The eigenvalues are always listed in descending order by magnitude as we see here when we compute their modulus and arguments</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="kw">Mod</span>(<span class="kw">eigen</span>(A)<span class="op">$</span>values)</span></code></pre></div>
<pre><code>## [1] 0.9835927 0.2070688 0.2070688</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a><span class="kw">Arg</span>(<span class="kw">eigen</span>(A)<span class="op">$</span>values)<span class="op">/</span>(<span class="dv">2</span> <span class="op">*</span>pi)<span class="op">*</span><span class="dv">360</span></span></code></pre></div>
<pre><code>## [1]   0.00000  96.04223 -96.04223</code></pre>
<p>We can diagonalize this over the complex numbers.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1"></a>P =<span class="st"> </span><span class="kw">eigen</span>(A)<span class="op">$</span>vectors</span>
<span id="cb60-2"><a href="#cb60-2"></a><span class="kw">zapsmall</span>(<span class="kw">solve</span>(P) <span class="op">%*%</span><span class="st"> </span>A <span class="op">%*%</span><span class="st"> </span>P)</span></code></pre></div>
<pre><code>##              [,1]                  [,2]                  [,3]
## [1,] 0.9835927+0i  0.0000000+0.0000000i  0.0000000+0.0000000i
## [2,] 0.0000000+0i -0.0217964+0.2059185i  0.0000000+0.0000000i
## [3,] 0.0000000+0i  0.0000000+0.0000000i -0.0217964-0.2059185i</code></pre>
<p>It has complex eigenvalues on the diagonal and requires using the complex vectors in our basis. Often, this is not what we want to do if our matrix has real entries and comes from a real-valued problem.</p>
<p>Instead, let’s rotation-dilationalize this matrix. The block diagonalization consists of a 1x1 block of the real eigenvalue and a 2x2 block of the rotation-dilation part of the complex eigenvalues.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a>vecs =<span class="st"> </span><span class="kw">eigen</span>(A)<span class="op">$</span>vectors</span>
<span id="cb62-2"><a href="#cb62-2"></a>P =<span class="st"> </span><span class="kw">Re</span>(<span class="kw">cbind</span>(vecs[,<span class="dv">1</span>],<span class="kw">Im</span>(vecs[,<span class="dv">2</span>]),<span class="kw">Re</span>(vecs[,<span class="dv">2</span>])))</span>
<span id="cb62-3"><a href="#cb62-3"></a>P</span></code></pre></div>
<pre><code>##            [,1]       [,2]        [,3]
## [1,] 0.31754239  0.0000000  0.68209367
## [2,] 0.05811107 -0.5896338 -0.06241245
## [3,] 0.94646180  0.4256233 -0.04505202</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1"></a><span class="kw">zapsmall</span>(<span class="kw">solve</span>(P) <span class="op">%*%</span><span class="st"> </span>A <span class="op">%*%</span><span class="st"> </span>P)</span></code></pre></div>
<pre><code>##           [,1]       [,2]       [,3]
## [1,] 0.9835927  0.0000000  0.0000000
## [2,] 0.0000000 -0.0217964 -0.2059185
## [3,] 0.0000000  0.2059185 -0.0217964</code></pre>
<p>In 3 dimensions, there the geometry is as follows:
* there is one basis vector, corresponding to the real eigenvalue <span class="math inline">\(\lambda = 0.985\)</span>
* there is a plane in which the system rotates by <span class="math inline">\(\theta = 96\)</span> degrees and contracts by <span class="math inline">\(r = 0.207\)</span>.
* thus, the complex part dies off pretty quickly (<span class="math inline">\(r = 0.207\)</span>), and it converges to the dominant real eigenvector, which is also dying off but more slowly (<span class="math inline">\(r = 0.983\)</span>)</p>
<p>We can see this in the traectory plot below. The oscillating part at the beginning comes from the complex eigenvalues as they quickly die off and the system converges to the dominant real eigenvector.</p>
<p><img src="09-geometry_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
},
"search": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
