
#  Problem Set 6

* Due: Tuesday March 02 by 11:59am CST. 
* Upload your solutions to Moodle in a PDF. 
* You can download the [Rmd source file  for this problem set](https://github.com/Tom-Halverson/math236_s21/blob/main/PS6-problem-set-6.Rmd).


The Problem Set covers sections 5.1, 5.2, 5.3, 5.5.



## Rain and Sunshine Revisited

On PS4, we encountered the rain-sunshine matrix $A$ below
$$
A = \begin{bmatrix}
1/2 & 1/10 \\
1/2 & 9/10 \\
\end{bmatrix}.
$$
Perform the following calculations **by hand** and show your work.

a. Find the characteristic polynomial of $A$ and find its eigenvalues.

a. Find an eigenvector for each eigenvalue and describe the eigenspaces.

a. Diagonalize $A$.

a.  Use your answer to (c) to give a formula for $A^n$ and use this formula to compute $\displaystyle{\lim_{n\to \infty}} A^n$.

a. Write a loop in `R` that starts with the vector `v = c(1,0)` (i.e., a rainy day vector) and applies the matrix `A = cbind(c(1/2,1/2),c(1/10,9/10))` over and over again (100 times). Explain how your answer compares to the answer to the previous problem.




## The Square Root of a Matrix?

The matrix $A  =\begin{bmatrix} 7 & 2 \\ -4 & 1 \end{bmatrix}$ has characteristic polynomial
$\lambda^2 - 8 \lambda + 15 = (\lambda -3)(\lambda - 5).$


a. Describe the eigenspaces of $A$.
a. Diagonalize $A$.
a. Find a matrix that makes sense to call $\sqrt{A}$. Then show that when you square this matrix, you really do get matrix $A$.

## Matrix Reconstruction

An unknown $3 \times 3$ matrix $M$ has eigenvectors and corresponding eigenvalues:
$$
\mathsf{v}_1 = \begin{bmatrix} 1 \\ 2 \\ 1 \end{bmatrix}, \  \lambda_1 = 1;
\qquad
\mathsf{v}_2 = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix},\  \lambda_2 = \frac{9}{10};
\qquad
\mathsf{v}_3 = \begin{bmatrix} -1 \\ 1 \\ 0 \end{bmatrix},\  \lambda_3 = 0.
$$

a. Without the matrix $M$, compute $M^{10} \mathsf{v}$ where $\mathsf{v} = \begin{bmatrix}7\\3\\4\end{bmatrix}$.

a. Describe all vectors $\mathsf{v}$, if there are any, such that $M^{n} \mathsf{v}  \to {\bf 0}$ as $n \to \infty$.

a. Is it possible to reconstruct $M$ from the evidence given? If so, then do it!  If not, explain what further information is needed.

## Coyotes and Roadrunners

(This problem can be done by hand or in R) This summer, Macalester's Ordway Natural History Study Area will  be stocked with a population of coyotes and roadrunners so that Math 236 students can study real-life predator-prey dynamics. From similar experiments, we expect the predator-prey dynamics to be governed by linear model below. The eigenvalues of the matrix are also given.
$$
\begin{bmatrix} \phantom{\Big\vert} r_{t+1}\phantom{\Big\vert}  \\ \phantom{\Big\vert} c_{t+1}\phantom{\Big\vert}  \phantom{\Big\vert} \end{bmatrix}
=\left[
\begin{array}{cc}
\phantom{\Big\vert} \frac{57}{50} & -\frac{6}{50} \\
\phantom{\Big\vert} \frac{4}{50} & \frac{43}{50} \\
\end{array}
\right] \begin{bmatrix} \phantom{\Big\vert} r_t \phantom{\Big\vert}  \\ \phantom{\Big\vert} c_t \phantom{\Big\vert} \end{bmatrix}
=
 \begin{bmatrix} \phantom{\Big\vert} 
\frac{57}{50} r_t -  \frac{6}{50}  c_t \\ \phantom{\Big\vert} \frac{4}{50} r_t +  \frac{43}{50} c_t \end{bmatrix},
$$
The eigenvalues of this matrix are:
$$
\lambda_1 =  \frac{11}{10} =  \frac{55}{50}, \qquad \lambda_2 =  \frac{9}{10} = \frac{45}{50}
$$
And eigenvalues and eigenvectors are:

```{r}
A = cbind(c(57/50,4/50),c(-6/50,43/50))
eigen(A)
```

a. Find  corresponding eigenvectors and \emph{diagonalize} this matrix.



a. If $r_0 =  10$ roadrunners and $c_0 = 15$ coyotes are introduced to the area, then give \emph{closed formulas} for the population of coyotes $c_t$ and roadrunners $r_t$ after $t$ years.


a.  In the long-term, in this model, what is the ratio of roadrunners to coyotes?



a. When another college tried the same experiment in their Arboretum, they introduced $r_0 =  5$ roadrunners and $c_0 = 10$ coyotes and both populations  quickly died off.  Explain why this is happening (using the model) and give the rate at which the populations die off.


## Matrices With Same Eigenvectors Commute





