
# Problem Set 7

* Due: Tuesday March 09 by 11:59am CST. 
* Upload your solutions to Moodle in a PDF. 
* Please feel free to **use RStudio for all calculations, including row reduction, matrix multiplication, eigenvector calculation and inverse matrices.**
* You can download the [Rmd source file  for this problem set](https://github.com/Tom-Halverson/math236_fs21/blob/main/PS7-problem-set-7.Rmd).

This problem set covers [Network Centralities] and Sections 6.1, 6.2, and 6.3 on Orthogonal Projections.



## The Rise of Moscow

Read [Network Centralities] and analyze the network of trade routes in medieval Russia given to you there.

a. Create a vector containing the normalized Degree Centralities. See Section \@ref(degree-centrality) for help.

a. Create a vector containing the Gould Index values. See Section \@ref(gould-index-summary) for help.

a. Plot the network where the size of the vertices is determined by Gould's Index and the size of the label is determined by degree centrality.

a. Create a data frame that contains Gould's Index and Degree Centralities. The rows should be labeled with the city names and the columns should be named by the centrality measures.  Sort according to Gould's Index.

a. Use Gould's Index to decide whether Moscow's dominance was solely due to its geographic location.

a. Compare the Gould's Index and Degree Centrality rankings and note any interesting findings. See Section \@ref(step-5) for help.


## Orthogonal Complements


Here are two subspaces of $\mathbb{R}^5$ that we have seen before
$$
\begin{align}
\mathsf{Z} & = \left\{ \begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \\ x_5 \end{bmatrix} \ \bigg\vert \ x_1 + x_2 + x_3 + x_4 + x_5 = 0 \right\}.
\\
\mathsf{F} & = \left\{ \begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \\ x_5 \end{bmatrix} \ \bigg\vert \  x_3 =  x_1 + x_2, x_4 = x_2 + x_3, x_5 = x_3 + x_4 \right\}.
\end{align}
$$
Find the orthogonal complement of each subspace in $\mathbb{R}^5$. For each example, compute $\dim(W) + \dim(W^\perp)$.



